# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XRAiwl4fK_ztbRQ9-nuJibnRZYMhJMBa
"""

import streamlit as st
import pandas as pd

st.title("Block Blending App")
st.write("Upload your block data Excel file and select two blocks to see their blended quality and quantity.")

# Upload Excel file
uploaded_file = st.file_uploader("Upload Block Data Excel File", type=["xlsx"])

if uploaded_file:
    # Read Excel file
    block_df = pd.read_excel(uploaded_file)
    block_df.columns = block_df.columns.str.strip()  # Clean column names

    # Show block data preview
    st.subheader("Block Data Preview")
    st.dataframe(block_df)

    # Select two blocks
    blocks = block_df['Block'].unique().tolist()
    block1 = st.selectbox("Select Block 1", blocks)
    block2 = st.selectbox("Select Block 2", [b for b in blocks if b != block1])

    if st.button("Calculate Blended Quality"):
        # Get selected block data
        b1 = block_df[block_df['Block'] == block1].iloc[0]
        b2 = block_df[block_df['Block'] == block2].iloc[0]

        # Total volume
        total_volume = b1['Volume'] + b2['Volume']

        # Weighted average
        blended_silica = (b1['Silica'] * b1['Volume'] + b2['Silica'] * b2['Volume']) / total_volume
        blended_alumina = (b1['Alumina'] * b1['Volume'] + b2['Alumina'] * b2['Volume']) / total_volume

        # Show results
        st.success("Blended Result:")
        st.write(f"**Block 1:** {block1}")
        st.write(f"**Block 2:** {block2}")
        st.write(f"**Total Volume:** {total_volume:,.0f} m³")
        st.write(f"**Blended Silica (%):** {blended_silica:.2f}")
        st.write(f"**Blended Alumina (%):** {blended_alumina:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit